-- ZetaLog UK university seed data. GENERATED FILE — do not edit by hand.
-- Regenerate: node supabase/scripts/generate-seed.mjs
-- Source: https://raw.githubusercontent.com/Hipo/university-domains-list/master/world_universities_and_domains.json
-- Universities: 192
-- Idempotent: re-running is a no-op for existing slugs.
insert into public.universities (name, slug, domains) values ('Aberystwyth University', 'aberystwyth-university', array['aber.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('American InterContinental University - London', 'american-intercontinental-university-london', array['aiuniv.edu']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Anglia Ruskin University', 'anglia-ruskin-university', array['anglia.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Aston University', 'aston-university', array['aston.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Bath Spa University', 'bath-spa-university', array['bathspa.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Birkbeck College, University of London', 'birkbeck-college-university-of-london', array['bbk.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Birmingham City University', 'birmingham-city-university', array['bcu.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Bournemouth University', 'bournemouth-university', array['bournemouth.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Bridgwater & Taunton College', 'bridgwater-taunton-college', array['btc.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('British College of Osteopathic Medicine', 'british-college-of-osteopathic-medicine', array['bcom.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Brunel University Uxbridge', 'brunel-university-uxbridge', array['brunel.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Buckinghamshire New University', 'buckinghamshire-new-university', array['bucks.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Camberwell College of Arts', 'camberwell-college-of-arts', array['camb.linst.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Canterbury Christ Church University', 'canterbury-christ-church-university', array['canterbury.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Cardiff University', 'cardiff-university', array['cardiff.ac.uk', 'cf.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Cardiff and Vale College', 'cardiff-and-vale-college', array['cavc.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Central Saint Martins College of Art & Design', 'central-saint-martins-college-of-art-design', array['csm.linst.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Chelsea College of Art and Design', 'chelsea-college-of-art-and-design', array['chelsea.linst.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('City St George''s, University of London', 'city-st-george-s-university-of-london', array['citystgeorges.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('City St George''s, University of London (II)', 'city-st-george-s-university-of-london-ii', array['student.staffs.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('City St George''s, University of London (School of Health and Medical Sciences)', 'city-st-george-s-university-of-london-school-of-health-and-medical-sciences', array['sgul.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('City University', 'city-university', array['city.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Courtauld Institute of Art, University of London', 'courtauld-institute-of-art-university-of-london', array['courtauld.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Coventry University', 'coventry-university', array['coventry.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Cranfield University', 'cranfield-university', array['cranfield.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('De Montfort University Leicester', 'de-montfort-university-leicester', array['dmu.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('East Coast College', 'east-coast-college', array['eastcoast.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Edge Hill University', 'edge-hill-university', array['edgehill.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Edinburgh Napier University', 'edinburgh-napier-university', array['napier.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('European School of Economics', 'european-school-of-economics', array['eselondon.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Falmouth University', 'falmouth-university', array['falmouth.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Futureworks', 'futureworks', array['futureworks.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Glasgow Caledonian University', 'glasgow-caledonian-university', array['gcal.ac.uk', 'gcu.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Glasgow School of Art', 'glasgow-school-of-art', array['gsa.ac.uk', 'student.gsa.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Goldsmiths College, University of London', 'goldsmiths-college-university-of-london', array['gold.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('HULT Business School', 'hult-business-school', array['hult.edu']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Harlaxton College', 'harlaxton-college', array['college.harlaxton.co.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Heriot-Watt University', 'heriot-watt-university', array['hw.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Heythrop College, University of London', 'heythrop-college-university-of-london', array['heythrop.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Huron University USA in London', 'huron-university-usa-in-london', array['huron.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Imperial College London', 'imperial-college-london', array['ic.ac.uk', 'imperial.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Imperial College School of Medicine', 'imperial-college-school-of-medicine', array['med.ic.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Institue of Historical Research, University of London', 'institue-of-historical-research-university-of-london', array['ihr.sas.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Institute of Education, University of London', 'institute-of-education-university-of-london', array['ioe.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('International Centre for Isclamic Science', 'international-centre-for-isclamic-science', array['kolieh.com']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('International Colleges of Islamic Science', 'international-colleges-of-islamic-science', array['islamiccolleges.com']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Keele University', 'keele-university', array['keele.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('King''s College London, University of London', 'king-s-college-london-university-of-london', array['kcl.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Kingston University', 'kingston-university', array['kingston.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Leeds Beckett University', 'leeds-beckett-university', array['leedsbeckett.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Leeds Trinity University', 'leeds-trinity-university', array['leedstrinity.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Liverpool Hope University College', 'liverpool-hope-university-college', array['hope.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Liverpool John Moores University', 'liverpool-john-moores-university', array['ljmu.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('London College of Science & Technology', 'london-college-of-science-technology', array['lcst.ac']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('London Guildhall University', 'london-guildhall-university', array['lgu.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('London Institute of Management and Technology', 'london-institute-of-management-and-technology', array['limt.co.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('London Interdisciplinary School', 'london-interdisciplinary-school', array['lis.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('London Metropolitan University', 'london-metropolitan-university', array['londonmet.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('London School of Business & Finance', 'london-school-of-business-finance', array['lsbf.org.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('London School of Economics and Political Science, University of London', 'london-school-of-economics-and-political-science-university-of-london', array['lse.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('London School of Hygiene & Tropical Medicine, University of London', 'london-school-of-hygiene-tropical-medicine-university-of-london', array['lshtm.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('London School of Jewish Studies', 'london-school-of-jewish-studies', array['lsjs.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('London South Bank University', 'london-south-bank-university', array['mlsbu.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Loughborough University', 'loughborough-university', array['lboro.ac.uk', 'student.lboro.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Middlesbrough College', 'middlesbrough-college', array['mbro.ac.uk', 'middlesbro.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Middlesex University - London', 'middlesex-university-london', array['mdx.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('New College Swindon', 'new-college-swindon', array['newcollege.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Newcastle College', 'newcastle-college', array['ncl-coll.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Newcastle University', 'newcastle-university', array['ncl.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Newport International University', 'newport-international-university', array['niu.org.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Northumbria University', 'northumbria-university', array['northumbria.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Nottingham Trent University', 'nottingham-trent-university', array['ntu.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Open University', 'open-university', array['open.ac.uk', 'ou.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Oxford Brookes University', 'oxford-brookes-university', array['brookes.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Queen Mary, University of London', 'queen-mary-university-of-london', array['qmul.ac.uk', 'qmw.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Richmond University - The American International University in London', 'richmond-university-the-american-international-university-in-london', array['richmond.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Roehampton University of Surrey', 'roehampton-university-of-surrey', array['roehampton.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Royal Academy of Music, University of London', 'royal-academy-of-music-university-of-london', array['ram.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Royal College of Art', 'royal-college-of-art', array['network.rca.ac.uk', 'rca.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Royal College of Music, University of London', 'royal-college-of-music-university-of-london', array['rcm.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Royal Free Hospital School of Medicine, University of London', 'royal-free-hospital-school-of-medicine-university-of-london', array['rfhsm.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Royal Holloway University of London', 'royal-holloway-university-of-london', array['rhul.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Royal Holloway and Bedford New College', 'royal-holloway-and-bedford-new-college', array['rh.ac.uk', 'rhbnc.ac.uk', 'royalholloway.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Runshaw College', 'runshaw-college', array['runshaw.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Saint George''s Hospital Medical School, University of London', 'saint-george-s-hospital-medical-school-university-of-london', array['sghms.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Schiller International University, London', 'schiller-international-university-london', array['schillerlondon.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('School of Advanced Study, University of London', 'school-of-advanced-study-university-of-london', array['sas.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('School of Oriental and African Studies, University of London', 'school-of-oriental-and-african-studies-university-of-london', array['soas.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('School of Pharmacy, University of London', 'school-of-pharmacy-university-of-london', array['ulsop.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('School of Slavonic and East European Studies, University of London', 'school-of-slavonic-and-east-european-studies-university-of-london', array['ssees.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Scotland''s Rural College (SRUC)', 'scotland-s-rural-college-sruc', array['sruc.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Sheffield Hallam University', 'sheffield-hallam-university', array['shu.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Sotheby´s Institute of Art - London', 'sotheby-s-institute-of-art-london', array['sothebysinstitutelondon.com']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('South Bank University', 'south-bank-university', array['sbu.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Southampton Solent University', 'southampton-solent-university', array['solent.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('St Mary''s University', 'st-mary-s-university', array['stmarys.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('St.Patrick''s International College, London', 'st-patrick-s-international-college-london', array['st-patricks.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Staffordshire University', 'staffordshire-university', array['staffs.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Stratford College London', 'stratford-college-london', array['sclondon.ac']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Swansea Metropolitan University', 'swansea-metropolitan-university', array['smu.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Swansea University', 'swansea-university', array['swansea.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Thames Valley University', 'thames-valley-university', array['tvu.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('The American University in London', 'the-american-university-in-london', array['aul.edu']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('The Manchester Metropolitan University', 'the-manchester-metropolitan-university', array['mmu.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('The Queen''s University Belfast', 'the-queen-s-university-belfast', array['qub.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('The Robert Gordon University', 'the-robert-gordon-university', array['rgu.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('The University of Sheffield', 'the-university-of-sheffield', array['shef.ac.uk', 'sheffield.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Trinity College Bristol', 'trinity-college-bristol', array['trinitycollegebristol.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Trinity College Carmarthen', 'trinity-college-carmarthen', array['trinity-cm.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Trinity College of Music', 'trinity-college-of-music', array['tcm.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Ulster University', 'ulster-university', array['ulst.ac.uk', 'ulster.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('United Medical and Dental Schools, University of London', 'united-medical-and-dental-schools-university-of-london', array['umds.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University Campus Suffolk', 'university-campus-suffolk', array['ucs.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University College London, University of London', 'university-college-london-university-of-london', array['ucl.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Aberdeen', 'university-of-aberdeen', array['abdn.ac.uk', 'aberdeen.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Abertay Dundee', 'university-of-abertay-dundee', array['abertay.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Bath', 'university-of-bath', array['bath.ac.uk', 'bath.edu']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Bedfordshire', 'university-of-bedfordshire', array['beds.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Birmingham', 'university-of-birmingham', array['bham.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Bolton', 'university-of-bolton', array['bolton.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Bradford', 'university-of-bradford', array['brad.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Brighton', 'university-of-brighton', array['bton.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Bristol', 'university-of-bristol', array['bris.ac.uk', 'bristol.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Buckingham', 'university-of-buckingham', array['buck.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Cambridge', 'university-of-cambridge', array['cam.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Central Lancashire', 'university-of-central-lancashire', array['uclan.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Chester', 'university-of-chester', array['chester.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Cumbria', 'university-of-cumbria', array['cumbria.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Derby', 'university-of-derby', array['derby.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Dundee', 'university-of-dundee', array['dundee.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Durham', 'university-of-durham', array['dur.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of East Anglia', 'university-of-east-anglia', array['uea.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of East London', 'university-of-east-london', array['uel.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Edinburgh', 'university-of-edinburgh', array['ed.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Essex', 'university-of-essex', array['essex.ac.uk', 'sx.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Exeter', 'university-of-exeter', array['ex.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Glamorgan', 'university-of-glamorgan', array['glam.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Glasgow', 'university-of-glasgow', array['gla.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Gloucestershire', 'university-of-gloucestershire', array['glos.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Greenwich', 'university-of-greenwich', array['gre.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Halifax, Birmingham Campus', 'university-of-halifax-birmingham-campus', array['halifaxuni.ac']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Hertfordshire', 'university-of-hertfordshire', array['herts.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Huddersfield', 'university-of-huddersfield', array['hud.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Hull', 'university-of-hull', array['hull.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Kent at Canterbury', 'university-of-kent-at-canterbury', array['ukc.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Lancaster', 'university-of-lancaster', array['lancs.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Leeds', 'university-of-leeds', array['leeds.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Leicester', 'university-of-leicester', array['le.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Lincoln', 'university-of-lincoln', array['lincoln.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Liverpool', 'university-of-liverpool', array['liv.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of London', 'university-of-london', array['london.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Manchester', 'university-of-manchester', array['man.ac.uk', 'manchester.ac.uk', 'mbs.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of North London', 'university-of-north-london', array['unl.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Northampton', 'university-of-northampton', array['northampton.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Nottingham', 'university-of-nottingham', array['nottingham.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Oxford', 'university-of-oxford', array['ox.ac.uk', 'oxford.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Paisley', 'university-of-paisley', array['paisley.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Plymouth', 'university-of-plymouth', array['plymouth.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Portsmouth', 'university-of-portsmouth', array['myport.ac.uk', 'myport.port.ac.uk', 'port.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Reading', 'university-of-reading', array['rdg.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Salford', 'university-of-salford', array['salford.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Southampton', 'university-of-southampton', array['soton.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of St. Andrews', 'university-of-st-andrews', array['st-and.ac.uk', 'st-andrews.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Stirling', 'university-of-stirling', array['stir.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Strathclyde', 'university-of-strathclyde', array['strath.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Sunderland', 'university-of-sunderland', array['sunderland.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Surrey', 'university-of-surrey', array['surrey.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Sussex', 'university-of-sussex', array['sussex.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Teesside', 'university-of-teesside', array['tees.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Wales', 'university-of-wales', array['wales.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Wales College of Medicine', 'university-of-wales-college-of-medicine', array['uwcm.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Wales Institute, Cardiff', 'university-of-wales-institute-cardiff', array['uwic.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Wales, Bangor', 'university-of-wales-bangor', array['bangor.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Wales, Lampeter', 'university-of-wales-lampeter', array['lamp.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Wales, Newport', 'university-of-wales-newport', array['newport.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Wales, Swansea', 'university-of-wales-swansea', array['swan.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Warwick', 'university-of-warwick', array['warwick.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Westminster', 'university-of-westminster', array['westminster.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Wolverhampton', 'university-of-wolverhampton', array['wlv.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of Worcester', 'university-of-worcester', array['worc.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of York', 'university-of-york', array['york.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of the Arts London', 'university-of-the-arts-london', array['arts.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('University of the West of England, Bristol', 'university-of-the-west-of-england-bristol', array['uwe.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Up Learn Business School', 'up-learn-business-school', array['uplearnbusinessschool.com']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Wakefield College', 'wakefield-college', array['wakefield.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Warnborough University', 'warnborough-university', array['warnborough.edu']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('West Herts College', 'west-herts-college', array['student.westherts.ac.uk', 'westherts.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('West Suffolk College', 'west-suffolk-college', array['wsc.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('William Gilbert College', 'william-gilbert-college', array['williamgilbert.co.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('Wimbledon School of Art', 'wimbledon-school-of-art', array['wimbledon.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('York St. John University', 'york-st-john-university', array['yorksj.ac.uk']::text[]) on conflict (slug) do nothing;
insert into public.universities (name, slug, domains) values ('ifs University College', 'ifs-university-college', array['ifslearning.ac.uk']::text[]) on conflict (slug) do nothing;
