import { parseProblem, type Operator, type Problem } from '../problems';
import type { GameEvent, GameRecord, OperandRange, ZetamacSettings } from '../schemas';
import type { ProblemOutcome, RecomputedScore } from '../score';

/**
 * Statistical conformity of a recomputed game's problem stream to Zetamac's
 * own generator, given the settings the record claims. This is the W6
 * anti-tamper layer: a cheater who rewrites the DISPLAYED problems (e.g. every
 * problem becomes "2 + 2") produces an internally consistent stream — every
 * answer matches its problem — that was nonetheless never generated by
 * Zetamac. These checks reconstruct what the real generator can and cannot
 * emit and flag streams that fall outside it.
 *
 * Ground truth is `apps/extension/test/fixtures/zetamac-app.js`, a captured
 * copy of Zetamac's own game script. The predicates below cite the exact
 * behaviour they encode.
 */

/** A hard, deterministic impossibility: the stream could not come from the generator. */
export interface ProblemViolation {
  readonly rule: 'range-nonconforming';
  readonly detail: string;
}

/** A statistical implausibility: legitimate under the generator only with vanishing probability. */
export interface ProblemFlag {
  readonly rule: 'operation-mix' | 'operand-marginal' | 'low-entropy' | 'problem-switch';
  readonly detail: string;
}

/** The result of screening one recomputed game's problem stream. */
export interface ProblemConformity {
  readonly violations: readonly ProblemViolation[];
  readonly flags: readonly ProblemFlag[];
}

/** True iff `value` lies within the inclusive operand range `[min, max]`. */
function inRange(value: number, range: OperandRange): boolean {
  return value >= range.min && value <= range.max;
}

/**
 * True iff `problem` is producible by the configured Zetamac generator.
 *
 * Derived directly from the fixture generators (fixture line numbers refer to
 * `apps/extension/test/fixtures/zetamac-app.js`):
 *
 * - **`+` (pg_add, L24–32):** `left = U[add_left]`, `right = U[add_right]`, so
 *   both operands must fall in their own add ranges.
 * - **`-` (pg_sub, L33–43):** draws `first = U[add_left]`, `second = U[add_right]`
 *   then shows `left = first + second`, `right = first`. Subtraction is the
 *   reverse of addition: the shown `right` is the addend `first` (∈ add_left)
 *   and the answer `left − right` is `second` (∈ add_right). With Zetamac's
 *   default add_right floor of 2, an answer below 2 (e.g. "4 − 3", "2 − 2") is
 *   impossible.
 * - **`*` (pg_mul, L44–52):** `left = U[mul_left]`, `right = U[mul_right]`. The
 *   default mul_left cap of 12 means a legitimate product never shows a left
 *   factor above 12.
 * - **`/` (pg_div, L53–65):** draws `first = U[mul_left]` (nonzero) and
 *   `second = U[mul_right]`, then shows `left = first * second`, `right = first`.
 *   Division is the reverse of multiplication: the shown `right` is the divisor
 *   `first` (∈ mul_left, nonzero) and the exact quotient `left / right` is
 *   `second` (∈ mul_right). A non-integer quotient, or a quotient below the
 *   default mul_right floor of 2 (e.g. "2 ÷ 2"), is impossible.
 *
 * A disabled operation (fixture L66–78: only enabled `pgs` are ever drawn) can
 * never appear, so its problems are non-producible regardless of operands.
 */
export function producibleUnderSettings(problem: Problem, settings: ZetamacSettings): boolean {
  switch (problem.op) {
    case '+':
      return (
        settings.addEnabled &&
        inRange(problem.left, settings.addLeft) &&
        inRange(problem.right, settings.addRight)
      );
    case '-':
      return (
        settings.subEnabled &&
        inRange(problem.right, settings.addLeft) &&
        inRange(problem.left - problem.right, settings.addRight)
      );
    case '*':
      return (
        settings.mulEnabled &&
        inRange(problem.left, settings.mulLeft) &&
        inRange(problem.right, settings.mulRight)
      );
    case '/':
      return (
        settings.divEnabled &&
        problem.right !== 0 &&
        inRange(problem.right, settings.mulLeft) &&
        problem.left % problem.right === 0 &&
        inRange(problem.left / problem.right, settings.mulRight)
      );
  }
}

/** Parse every solved outcome into a {@link Problem}, dropping any unparseable text. */
function parsedOutcomes(outcomes: readonly ProblemOutcome[]): readonly Problem[] {
  const problems: Problem[] = [];
  for (const outcome of outcomes) {
    const parsed = parseProblem(outcome.text);
    if (parsed.ok) problems.push(parsed.value);
  }
  return problems;
}

/**
 * Hard range-conformity check: any solved problem the configured generator
 * could not have produced is an impossible stream (same class as non-monotonic
 * timestamps) and rejects outright.
 */
function checkRangeConformity(
  problems: readonly Problem[],
  settings: ZetamacSettings,
): readonly ProblemViolation[] {
  const nonconforming = problems.filter((problem) => !producibleUnderSettings(problem, settings));
  if (nonconforming.length === 0) return [];
  // length >= 1 here, so slice(0, 1) yields exactly one example with no
  // undefined-index branch to leave uncovered.
  const example = nonconforming
    .slice(0, 1)
    .map((p) => `${String(p.left)} ${p.op} ${String(p.right)}`)
    .join('');
  return [
    {
      rule: 'range-nonconforming',
      detail:
        `${String(nonconforming.length)} problem(s) impossible under the claimed settings ` +
        `(e.g. ${example})`,
    },
  ];
}

/** Below this many solved problems the operation-mix test is underpowered. */
export const MIX_MIN_PROBLEMS = 30;

/** Family-wise false-positive budget for the operation-mix test on legitimate play. */
export const MIX_FALSE_POSITIVE_RATE = 1e-4;

/** Below this many solved problems the operand-marginal test is underpowered. */
export const MARGINAL_MIN_PROBLEMS = 30;

/** Family-wise false-positive budget for the operand-marginal test on legitimate play. */
export const MARGINAL_FALSE_POSITIVE_RATE = 1e-4;

/**
 * Below this many solved problems the repetition/entropy test does not run.
 * The birthday bound self-regulates at small n — on the default space the
 * flag threshold is multiplicity 3 at n = 8 (family FP ≤ 2.3e-5) and 4 at
 * n = 19 (FP ≤ 3.3e-7) — so the gate only excludes degenerate handfuls of
 * problems; 8 is low enough to catch a trivial-swap 30-second game
 * ("2 + 2" × 19), which a gate of 20 would have waved through.
 */
export const ENTROPY_MIN_PROBLEMS = 8;

/** Family-wise false-positive budget for the repetition/entropy test on legitimate play. */
export const ENTROPY_FALSE_POSITIVE_RATE = 1e-4;

/** The operations enabled by a settings configuration, in canonical order. */
function enabledOperators(settings: ZetamacSettings): readonly Operator[] {
  const ops: Operator[] = [];
  if (settings.addEnabled) ops.push('+');
  if (settings.subEnabled) ops.push('-');
  if (settings.mulEnabled) ops.push('*');
  if (settings.divEnabled) ops.push('/');
  return ops;
}

/**
 * True when division is enabled and its divisor range spans zero, i.e. the
 * generator can draw `first = 0` and re-roll (fixture L56 returns undefined
 * and problemGen re-draws, L79–85). Re-rolls skew the uniform-draw
 * assumptions the statistical rules rest on, so they all abstain here.
 */
function divisorSpansZero(settings: ZetamacSettings): boolean {
  return settings.divEnabled && settings.mulLeft.min <= 0 && settings.mulLeft.max >= 0;
}

/**
 * Operation-mix plausibility.
 *
 * The generator (fixture L79–85) draws each problem's operation uniformly from
 * the `k` enabled ones, so over `n` problems each enabled op's count is
 * Binomial(n, 1/k). We flag a game when some enabled op's observed share is
 * implausibly far from 1/k.
 *
 * Bound: Hoeffding's inequality gives, for one op,
 * `P(|share − 1/k| ≥ t) ≤ 2·exp(−2 n t²)`. A union bound over all `k` ops
 * (two-sided) bounds the family-wise false-positive rate by
 * `2k·exp(−2 n t²)`. Setting that equal to {@link MIX_FALSE_POSITIVE_RATE}
 * and solving gives the threshold `t = sqrt( ln(2k/α) / (2n) )`. The bound is
 * distribution-free and holds for the exact Binomial marginals, so legitimate
 * play trips it with probability below α (verified by property test). It is
 * deliberately conservative — it exists to catch gross manipulation (an op that
 * never appears, or one that is nearly everything), not subtle drift.
 *
 * The uniform-draw assumption is exact only when no enabled generator can
 * re-roll. The single exception is division when the divisor range spans zero
 * (fixture L56 returns `null`, forcing a re-draw), so the test abstains there.
 */
function checkOperationMix(
  problems: readonly Problem[],
  settings: ZetamacSettings,
): readonly ProblemFlag[] {
  const n = problems.length;
  if (n < MIX_MIN_PROBLEMS) return [];
  if (divisorSpansZero(settings)) return [];

  const enabled = enabledOperators(settings);
  const k = enabled.length;
  if (k < 2) return [];

  const threshold = Math.sqrt(Math.log((2 * k) / MIX_FALSE_POSITIVE_RATE) / (2 * n));
  const counts = new Map<Operator, number>();
  for (const problem of problems) counts.set(problem.op, (counts.get(problem.op) ?? 0) + 1);

  const expected = 1 / k;
  const deviating = enabled.filter(
    (op) => Math.abs((counts.get(op) ?? 0) / n - expected) > threshold,
  );
  if (deviating.length === 0) return [];

  const shares = deviating
    .map((op) => `${op} at ${(((counts.get(op) ?? 0) / n) * 100).toFixed(0)}%`)
    .join(', ');
  return [
    {
      rule: 'operation-mix',
      detail:
        `operation shares deviate from the uniform ${(expected * 100).toFixed(0)}% ` +
        `over ${String(n)} problems (${shares})`,
    },
  ];
}

/** Inclusive integer range cardinality, always ≥ 1 since `min ≤ max`. */
function rangeSize(range: OperandRange): number {
  return range.max - range.min + 1;
}

/** One uniform observable of one operation: where to read it and its exact null law. */
interface MarginalSlot {
  /** Human-readable slot name for flag details, e.g. `"* left"`. */
  readonly label: string;
  /** The midpoint ⌊(min+max)/2⌋ of the slot's configured range. */
  readonly mid: number;
  /** Exact P(value ≤ mid) for a uniform draw on the integer range. */
  readonly p0: number;
  /** Extract the slot's value from a parsed problem; null when unobservable. */
  readonly observe: (problem: Problem) => number | null;
}

/** Build one slot: exact `p0 = (mid − min + 1)/M` from the integer range (never assumed ½). */
function slotFor(
  label: string,
  range: OperandRange,
  observe: (problem: Problem) => number | null,
): MarginalSlot {
  const mid = Math.floor((range.min + range.max) / 2);
  return { label, mid, p0: (mid - range.min + 1) / rangeSize(range), observe };
}

/**
 * The uniform observables of each enabled operation (fixture L14–23: every
 * operand is drawn by `randGen`, uniform on its inclusive range):
 * - `+` (L24–32): left ~ U[add_left], right ~ U[add_right].
 * - `-` (L33–43): subtrahend (shown right) ~ U[add_left]; answer (left−right)
 *   ~ U[add_right]. The shown minuend is a SUM of two uniforms — not uniform —
 *   so it is deliberately not tested.
 * - `*` (L44–52): left ~ U[mul_left], right ~ U[mul_right].
 * - `/` (L53–65): divisor (shown right) ~ U[mul_left]; quotient (left/right)
 *   ~ U[mul_right]. The shown dividend is a product — not uniform. A zero
 *   divisor (only possible in an already-nonconforming problem) is skipped
 *   rather than observed as an infinite quotient.
 */
function marginalSlots(settings: ZetamacSettings): ReadonlyMap<Operator, readonly MarginalSlot[]> {
  const slots = new Map<Operator, readonly MarginalSlot[]>();
  if (settings.addEnabled) {
    slots.set('+', [
      slotFor('+ left', settings.addLeft, (p) => p.left),
      slotFor('+ right', settings.addRight, (p) => p.right),
    ]);
  }
  if (settings.subEnabled) {
    slots.set('-', [
      slotFor('- subtrahend', settings.addLeft, (p) => p.right),
      slotFor('- answer', settings.addRight, (p) => p.left - p.right),
    ]);
  }
  if (settings.mulEnabled) {
    slots.set('*', [
      slotFor('* left', settings.mulLeft, (p) => p.left),
      slotFor('* right', settings.mulRight, (p) => p.right),
    ]);
  }
  if (settings.divEnabled) {
    slots.set('/', [
      slotFor('/ divisor', settings.mulLeft, (p) => p.right),
      slotFor('/ quotient', settings.mulRight, (p) => (p.right === 0 ? null : p.left / p.right)),
    ]);
  }
  return slots;
}

/**
 * Operand-marginal plausibility.
 *
 * A tamperer who keeps the operation mix uniform and every problem in range
 * can still trivialise the game by drawing operands only from the easy (low)
 * end — e.g. 60 distinct problems of the form "2 + k", "k − 2", "2 × k",
 * "2k ÷ 2" with small k. Under the real generator each observable slot is
 * uniform on its range (see {@link marginalSlots}), so the count of a slot's
 * values at or below its midpoint over that op's n_j problems is
 * Binomial(n_j, p₀ⱼ) with p₀ⱼ computed exactly from the integer range.
 *
 * Statistics: K = (#slots) + 1 two-sided Hoeffding tests under one union
 * bound — one per slot, plus one POOLED test over all N = Σ n_j slot
 * observations (independent Bernoullis with non-identical means, which
 * Hoeffding permits; the pooled expectation is Σ n_j·p₀ⱼ). Each test uses
 * threshold `t_j = sqrt(ln(2K/α) / (2 n_j))` with its own sample size, so the
 * family false-positive rate on legitimate play is below
 * α = {@link MARGINAL_FALSE_POSITIVE_RATE} (property-tested).
 *
 * The pooled test carries the power at realistic lengths: a per-slot test
 * cannot fire below n_j > 2·ln(2K/α) ≈ 24 even for a maximal deviation, so a
 * balanced four-op 60-problem attack (n_j ≈ 15) would evade per-slot tests
 * entirely; pooling its ~120 observations catches it, while the per-slot
 * tests catch a single pinned operand in longer games.
 *
 * Abstentions mirror the mix rule: fewer than {@link MARGINAL_MIN_PROBLEMS}
 * problems, or a zero-spanning divisor range (generator re-rolls, L56).
 */
function checkOperandMarginals(
  problems: readonly Problem[],
  settings: ZetamacSettings,
): readonly ProblemFlag[] {
  const n = problems.length;
  if (n < MARGINAL_MIN_PROBLEMS) return [];
  if (divisorSpansZero(settings)) return [];
  const slotsByOp = marginalSlots(settings);
  if (slotsByOp.size === 0) return [];

  const tallies = new Map<Operator, { slot: MarginalSlot; count: number; low: number }[]>();
  for (const [op, slots] of slotsByOp) {
    tallies.set(
      op,
      slots.map((slot) => ({ slot, count: 0, low: 0 })),
    );
  }
  for (const problem of problems) {
    const opTallies = tallies.get(problem.op);
    if (opTallies === undefined) continue; // op disabled: already a hard violation
    for (const tally of opTallies) {
      const value = tally.slot.observe(problem);
      if (value === null) continue;
      tally.count += 1;
      if (value <= tally.slot.mid) tally.low += 1;
    }
  }

  const all = [...tallies.values()].flat();
  const familySize = all.length + 1;
  const logTerm = Math.log((2 * familySize) / MARGINAL_FALSE_POSITIVE_RATE);
  const deviating: string[] = [];
  let total = 0;
  let totalLow = 0;
  let expectedLow = 0;
  for (const { slot, count, low } of all) {
    total += count;
    totalLow += low;
    expectedLow += count * slot.p0;
    if (count === 0) continue;
    const threshold = Math.sqrt(logTerm / (2 * count));
    if (Math.abs(low / count - slot.p0) > threshold) {
      deviating.push(`${slot.label} at ${((low / count) * 100).toFixed(0)}% low`);
    }
  }
  if (total > 0) {
    const threshold = Math.sqrt(logTerm / (2 * total));
    if (Math.abs(totalLow / total - expectedLow / total) > threshold) {
      deviating.push(`all slots at ${((totalLow / total) * 100).toFixed(0)}% low`);
    }
  }
  if (deviating.length === 0) return [];

  return [
    {
      rule: 'operand-marginal',
      detail:
        `operand distributions implausible for uniform draws over ${String(n)} problems ` +
        `(${deviating.join('; ')})`,
    },
  ];
}

/** Range cardinality excluding zero, since a zero divisor is re-rolled (fixture L56). */
function nonZeroRangeSize(range: OperandRange): number {
  return rangeSize(range) - (range.min <= 0 && range.max >= 0 ? 1 : 0);
}

/**
 * The number of DISTINCT problems each enabled operation can produce, i.e. the
 * size of its sample space:
 * - add / sub: `|add_left| · |add_right|` (sub is a bijection of the same draw)
 * - mul: `|mul_left| · |mul_right|`
 * - div: `|mul_left \ {0}| · |mul_right|` (a zero divisor never yields a problem)
 */
function enabledSpaceSizes(settings: ZetamacSettings): readonly number[] {
  const addSize = rangeSize(settings.addLeft) * rangeSize(settings.addRight);
  const mulSize = rangeSize(settings.mulLeft) * rangeSize(settings.mulRight);
  const divSize = nonZeroRangeSize(settings.mulLeft) * rangeSize(settings.mulRight);
  const sizes: number[] = [];
  if (settings.addEnabled) sizes.push(addSize);
  if (settings.subEnabled) sizes.push(addSize);
  if (settings.mulEnabled) sizes.push(mulSize);
  if (settings.divEnabled) sizes.push(divSize);
  return sizes;
}

/**
 * Smallest multiplicity `C ≥ 2` that a single problem may reach before the
 * repetition is implausible, or `null` when even `n` identical draws are not
 * rare enough to distinguish from chance (a tiny operand space).
 *
 * Derivation: a specific problem `x` is drawn with probability at most
 * `pMax = 1/(k·M_min)` (uniform op, then uniform within the smallest space), so
 * its count `N_x ~ Binomial(n, pMax)` and
 * `P(N_x ≥ C) ≤ C(n,C)·pMax^C ≤ (n·pMax)^C / C!`. Union-bounding over all
 * `M_total` distinct producible problems (each ≤ pMax) gives a family-wise
 * `P(any problem repeats ≥ C) ≤ M_total · (n·pMax)^C / C!`. `C*` is the least
 * `C` making that bound below {@link ENTROPY_FALSE_POSITIVE_RATE}. Because
 * every real value is bounded by pMax, the true false-positive rate is even
 * lower, so legitimate play — including narrow-range games evaluated against
 * their own small space — stays under α.
 */
function birthdayThreshold(
  n: number,
  totalSpace: number,
  maxProbability: number,
  alpha: number,
): number | null {
  const expectedPerValue = n * maxProbability;
  let count = 2;
  // bound_C = totalSpace · expectedPerValue^C / C!, updated multiplicatively.
  let bound = (totalSpace * expectedPerValue * expectedPerValue) / 2;
  while (bound >= alpha) {
    if (count >= n) return null;
    count += 1;
    bound = (bound * expectedPerValue) / count;
  }
  return count;
}

/**
 * Repetition / entropy check. The generator draws problems independently, so
 * the same problem recurring far beyond the birthday-bound expectation for the
 * CLAIMED operand space is evidence the stream was rewritten (e.g. "2 + 2"
 * forever). See {@link birthdayThreshold} for the bound; a narrow legitimate
 * game is judged against its own small space and so is not flagged.
 */
function checkEntropy(
  problems: readonly Problem[],
  settings: ZetamacSettings,
): readonly ProblemFlag[] {
  const n = problems.length;
  if (n < ENTROPY_MIN_PROBLEMS) return [];

  const sizes = enabledSpaceSizes(settings);
  if (sizes.length === 0) return [];
  const minSpace = Math.min(...sizes);
  // A zero-only divisor range makes div's producible set empty (the real
  // generator would re-roll forever): pMax would be infinite and the bound
  // NaN. Checked before the broader re-roll abstention so it stays reachable.
  if (minSpace === 0) return [];
  // pMax assumes every enabled op is drawn with probability exactly 1/k; a
  // re-rolling divisor (fixture L56) inflates the other ops' probabilities,
  // so — like the mix rule — the test abstains rather than mis-bound.
  if (divisorSpansZero(settings)) return [];
  const totalSpace = sizes.reduce((sum, size) => sum + size, 0);
  const maxProbability = 1 / (sizes.length * minSpace);

  const threshold = birthdayThreshold(n, totalSpace, maxProbability, ENTROPY_FALSE_POSITIVE_RATE);
  if (threshold === null) return [];

  const counts = new Map<string, number>();
  let maxMultiplicity = 0;
  for (const problem of problems) {
    const key = `${String(problem.left)}${problem.op}${String(problem.right)}`;
    const next = (counts.get(key) ?? 0) + 1;
    counts.set(key, next);
    if (next > maxMultiplicity) maxMultiplicity = next;
  }
  if (maxMultiplicity < threshold) return [];

  return [
    {
      rule: 'low-entropy',
      detail:
        `a single problem repeats ${String(maxMultiplicity)}× over ${String(n)} problems; ` +
        `≥ ${String(threshold)} is implausible for the claimed operand space`,
    },
  ];
}

/**
 * Problem-switch anomaly. Zetamac renders a new problem only after the current
 * one is accepted (fixture L88–98, 116–126: `problemGeng` runs inside the
 * accept handler). Two `problem` events with no `accepted` between them mean an
 * unsolved problem was re-rendered — a hallmark of DOM tampering. Small counts
 * can be re-render noise, so this is a reviewable flag (not a hard failure)
 * that records the count.
 */
function checkProblemSwitches(events: readonly GameEvent[]): readonly ProblemFlag[] {
  let pending = false;
  let switches = 0;
  for (const event of events) {
    if (event.kind === 'problem') {
      if (pending) switches += 1;
      pending = true;
    } else if (event.kind === 'accepted') {
      pending = false;
    }
  }
  if (switches === 0) return [];
  return [
    {
      rule: 'problem-switch',
      detail: `${String(switches)} unsolved problem re-render(s)`,
    },
  ];
}

/**
 * Screen a recomputed game's problem stream for tampering. Range violations
 * are hard (reject); the statistical flags are grounds for quarantine.
 */
export function checkProblems(record: GameRecord, recomputed: RecomputedScore): ProblemConformity {
  const problems = parsedOutcomes(recomputed.outcomes);
  const violations = checkRangeConformity(problems, record.settings);
  const flags = [
    ...checkOperationMix(problems, record.settings),
    ...checkOperandMarginals(problems, record.settings),
    ...checkEntropy(problems, record.settings),
    ...checkProblemSwitches(record.events),
  ];
  return { violations, flags };
}
